image: node:12

cache:
    paths:
        - node_modules/

before_script:
    - npm --color="always" install

build:
    stage: build
    script:
        - npx tsc
        - PACKAGE=`npm --color="always" pack`
        - mv "$PACKAGE" saltpack.tgz
    artifacts:
        paths:
            - dist
            - saltpack.tgz

test-10:
    image: node:10
    script:
        - npm run test
    dependencies:
        - build

test-12:
    image: node:12
    script:
        - npm run test
    dependencies:
        - build

test-14:
    image: node:14
    script:
        - npm run test
    dependencies:
        - build

publish-npm:
    stage: deploy
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm --color="always" publish
    dependencies:
        - build
    only:
        refs:
            - /^v.*$/
        variables:
            - $NPM_TOKEN
    except:
        - branches
    cache:
        paths:
            - node_modules/
        policy: pull

publish-github:
    stage: deploy
    script:
        # Update the package.json and package-lock.json
        # GitHub Package Repository now requires the `repository` field is the GitHub repository
        # This means the package publish to GitHub is different to the package published everywhere else
        - "node -e \"fs.writeFileSync('package.json', JSON.stringify((json => {json.repository = {type: 'git', url: 'https://github.com/' + process.env.GITHUB_REPOSITORY + '.git'}; return json;})(JSON.parse(fs.readFileSync('package.json', 'utf-8'))), null, 4) + '\\n', 'utf-8')\""

        - echo "//npm.pkg.github.com/:_authToken=${GITHUB_NPM_TOKEN}" > .npmrc
        - npm --color="always" --registry=https://npm.pkg.github.com/ publish
    dependencies:
        - build
    only:
        refs:
            - /^v.*$/
        variables:
            - $GITHUB_REPOSITORY
            - $GITHUB_NPM_TOKEN
    except:
        - branches
    cache:
        paths:
            - node_modules/
        policy: pull

publish-gitlab:
    stage: deploy
    script:
        - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" | sed s/^https:// > .npmrc
        - npm --color="always" --registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/ publish
    dependencies:
        - build
    only:
        refs:
            - /^v.*$/
        variables:
            - $GITLAB_NPM_PUBLISH
    except:
        - branches
    cache:
        paths:
            - node_modules/
        policy: pull
